# Generated by Django 5.0.3 on 2024-03-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
